apiVersion: apps/v1  
kind: Deployment     

metadata:
  name: sih-app-deployment  
spec:
  replicas: 1

  selector:
    matchLabels:
      app: sih-app  

  template:  
    metadata:
      labels:
        app: sih-app  
    
    spec: 
      containers:
      - name: job-app-server
        image: ayushsaini07/sihwebsite:latest  
        
        ports:
        - containerPort: 80  
